//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShellAdmin.AdminConnection {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminConnection.IAdmin", CallbackContract=typeof(ShellAdmin.AdminConnection.IAdminCallback))]
    public interface IAdmin {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdmin/AddGameTime")]
        void AddGameTime(double hour, double minute, int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdmin/AddGameTime")]
        System.Threading.Tasks.Task AddGameTimeAsync(double hour, double minute, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/Connect", ReplyAction="http://tempuri.org/IAdmin/ConnectResponse")]
        int Connect(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/Connect", ReplyAction="http://tempuri.org/IAdmin/ConnectResponse")]
        System.Threading.Tasks.Task<int> ConnectAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdmin/Disconnect")]
        void Disconnect(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdmin/Disconnect")]
        System.Threading.Tasks.Task DisconnectAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdmin/InfoMsg")]
        void InfoMsg(string msg, int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminChannel : ShellAdmin.AdminConnection.IAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminClient : System.ServiceModel.DuplexClientBase<ShellAdmin.AdminConnection.IAdmin>, ShellAdmin.AdminConnection.IAdmin {
        
        public AdminClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AdminClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AdminClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void AddGameTime(double hour, double minute, int id) {
            base.Channel.AddGameTime(hour, minute, id);
        }
        
        public System.Threading.Tasks.Task AddGameTimeAsync(double hour, double minute, int id) {
            return base.Channel.AddGameTimeAsync(hour, minute, id);
        }
        
        public int Connect(string Name) {
            return base.Channel.Connect(Name);
        }
        
        public System.Threading.Tasks.Task<int> ConnectAsync(string Name) {
            return base.Channel.ConnectAsync(Name);
        }
        
        public void Disconnect(int id) {
            base.Channel.Disconnect(id);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(int id) {
            return base.Channel.DisconnectAsync(id);
        }
    }
}
